/**
 *
 */
package com.javapractice.leetcode;

/**
 * @author Jianyu Feng
 * https://leetcode.com/problems/find-the-difference/
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 *
 */
public class FindTheDifference {
	public char findTheDifference(String s, String t) {
		int[] charMap = new int[26];

		for (char c:s.toCharArray()) {
			charMap[c-'a']++;
		}

		for (char c:t.toCharArray()) {
			charMap[c-'a']--;
			if (charMap[c-'a']<0) {
				return c;
			}
		}

		return 'a';
	}
}
